// Code generated by "pkgsyms.exe "; DO NOT EDIT.

package pkgsyms

var Pkg = Of("github.com/skillian/pkgsyms")

func init() {
	Pkg.Add(
		MakeType("NotFound", (*NotFound)(nil)),
		MakeType("Package", (*Package)(nil)),
		MakeFunc("Of", Of),
		MakeFunc("Lookup", Lookup),
		MakeType("Symbol", (*Symbol)(nil)),
		MakeType("Symbols", (*Symbols)(nil)),
		MakeFunc("MakeSymbols", MakeSymbols),
		MakeType("Const", (*Const)(nil)),
		MakeFunc("MakeConst", MakeConst),
		MakeType("Func", (*Func)(nil)),
		MakeFunc("MakeFunc", MakeFunc),
		MakeType("Type", (*Type)(nil)),
		MakeFunc("MakeType", MakeType),
		MakeType("Var", (*Var)(nil)),
	)
}
