// Code generated by "main -package pkgsyms_test -output=testsyms.go github.com/skillian/pkgsyms"; DO NOT EDIT.

package pkgsyms_test

import "github.com/skillian/pkgsyms"

var Pkg = pkgsyms.Of("github.com/skillian/pkgsyms")

func init() {
	Pkg.Add(
		pkgsyms.MakeType("Package", (*pkgsyms.Package)(nil)),
		pkgsyms.MakeFunc("Of", pkgsyms.Of),
		pkgsyms.MakeType("Symbol", (*pkgsyms.Symbol)(nil)),
		pkgsyms.MakeType("Symbols", (*pkgsyms.Symbols)(nil)),
		pkgsyms.MakeFunc("MakeSymbols", pkgsyms.MakeSymbols),
		pkgsyms.MakeType("Const", (*pkgsyms.Const)(nil)),
		pkgsyms.MakeFunc("MakeConst", pkgsyms.MakeConst),
		pkgsyms.MakeType("Func", (*pkgsyms.Func)(nil)),
		pkgsyms.MakeFunc("MakeFunc", pkgsyms.MakeFunc),
		pkgsyms.MakeType("Type", (*pkgsyms.Type)(nil)),
		pkgsyms.MakeFunc("MakeType", pkgsyms.MakeType),
		pkgsyms.MakeType("Var", (*pkgsyms.Var)(nil)),
	)
}
